name: Terraform + OPA Compliance

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply (only on main)"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

permissions:
  contents: read

concurrency:
  group: tf-opa-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_VERSION: "1.8.5"
  TF_WORKDIR: "./terraform"
  # Pin Conftest to v0.59.0 to avoid Rego v1 default in >= v0.60
  CONFTEST_VERSION: "v0.59.0"

jobs:
  plan_and_check:
    name: Terraform Plan + OPA Policy Check
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # ---- Install Conftest (pin + robust) ----
      - name: Install Conftest
        shell: bash
        run: |
          set -euo pipefail
          OS="Linux"
          ARCH="$(uname -m)"
          case "$ARCH" in
            x86_64|amd64) ARCH="x86_64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *) echo "Unsupported arch: $ARCH"; exit 1 ;;
          esac
          # Strip leading 'v' for asset filename (e.g., v0.59.0 -> 0.59.0)
          VER="${CONFTEST_VERSION#v}"
          ASSET="conftest_${VER}_${OS}_${ARCH}.tar.gz"
          URL="https://github.com/open-policy-agent/conftest/releases/download/${CONFTEST_VERSION}/${ASSET}"
          echo "Downloading $URL"
          curl -sSLf -o /tmp/conftest.tgz "$URL"
          tar -xzf /tmp/conftest.tgz -C /tmp
          sudo mv /tmp/conftest /usr/local/bin/conftest
          conftest --version

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -input=false -upgrade

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform plan -out plan.out

      - name: Export plan.json
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform show -json plan.out > plan.json

      - name: OPA Policy Check (Conftest)
        run: conftest test ${{ env.TF_WORKDIR }}/plan.json --policy policies/tfplan

      - name: Upload plan + artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-and-policy-artifacts
          path: |
            ${{ env.TF_WORKDIR }}/plan.out
            ${{ env.TF_WORKDIR }}/plan.json
          retention-days: 7

      - name: Terraform Apply (gated)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.apply == 'true' && github.ref == 'refs/heads/main' }}
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve plan.out
